name: Build and Release WordPress Plugin

on:
  release:
    types: [published]


jobs:
  build-and-release-plugin:
    name: Build and attach the WordPress plugin zip to the release
    runs-on: ubuntu-latest

    env:
      ZIP_NAME: tribe-alerts.zip
      ZIP_FOLDER: tribe-alerts
      SCOPED_FILES: "composer.json core.php vendor src"

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          tools: composer
          coverage: none
        env:
          COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create composer .env
        run: echo "${{ secrets.COMPOSER_ENV }}" > .env

      - name: Install composer dependencies
        run: composer install --no-progress --no-dev --no-suggest

      - name: Install PHP-Scoper
        run: wget https://github.com/humbug/php-scoper/releases/download/0.17.2/php-scoper.phar

      - name: Run PHP-Scoper
        run: php php-scoper.phar add-prefix --force

      - name: Copy scoped files back to source folder
        run: rsync -av build/ .

      - name: Create scoped autoloader
        run: composer dump-autoload --classmap-authoritative --no-dev

      - name: Clean up files
        run: rm -rf .env

      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'

      - name: Install node modules
        run: yarn install --prefer-offline

      - name: Build assets
        run: yarn prod

      - name: Create zip via git archive
        run: git archive --prefix ${{ env.ZIP_FOLDER }}/ --format=zip --worktree-attributes -o ${{ env.ZIP_NAME }} ${{ github.event.release.tag_name }}

      - name: Prepare scoped files for zipping
        run: mkdir ${{ env.ZIP_FOLDER }}; mv -t ${{ env.ZIP_FOLDER }} ${{ env.SCOPED_FILES }}

      - name: Update zip with scoped folders and file
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -ur ${{ env.ZIP_NAME }} ${{ env.ZIP_FOLDER }}/*

      - name: Upload to release
        uses: JasonEtco/upload-to-release@v0.1.1
        with:
          args: ${{ env.ZIP_NAME }} application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
